apiVersion: kubelet.config.k8s.io/v1beta1
kind: CredentialProviderConfig
{{! This isn't right as the condition is more than just whether `providers` is "truey" but whether any are enabled }}
{{#if settings.kubernetes.credential-providers.providers}}
providers:
{{#each settings.kubernetes.credential-providers.providers}}
{{#if this.enabled}}
  - name: {{this.name}}
    matchImages:
{{#each this.imagepatterns}}
      - {{this}}
{{/each}}
    defaultCacheDuration: {{default "12h" this.cacheduration}}
    apiVersion: credentialprovider.kubelet.k8s.io/v1beta1
{{#if this.name == "ecr-credential-provider"}}
    env:
      - name: PATH
        value: /bin:/usr/bin:/usr/local/bin
      - name: HOME
        value: /root
{{/if}}
{{/if}}
{{/each}}
{{else}}
providers: []
{{/if}}
