[package]
name = "hotdog"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/bottlerocket-os/hotdog/archive/b85b75576adbbd7e133b54d71ebc11a28acf40db/hotdog-b85b755.tar.gz"
sha512 = "9b2d5cb0e25d774d11dd6eb577e07af85f36fcd6e816b9df88d7ca1da273695f15ce6831026d28e68355512a07d0ac673b5ce9771d969f1c5ca4f14bc631deb8"
bundle-modules = [ "go" ]
bundle-path = "hotdog-b85b75576adbbd7e133b54d71ebc11a28acf40db"
bundle-output-path = "hotdog-b85b755-bundled.tar.gz"

[build-dependencies]
glibc = { path = "../glibc" }

[dependencies]
log4j2-hotpatch= { path = "../log4j2-hotpatch" }
